name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

   #   - name: Setup Hugo
    #    uses: peaceiris/actions-hugo@v2
     #   with:
      #    hugo-version: 'latest'
       #   extended: true
      - name: Install Hugo withdeploy
        run: |
          HUGO_VERSION=0.147.0
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          tar -xzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/hugo
          hugo version

      - name: Build Site
        run: hugo --config hugo.yaml
      - name: List Generated Files
        run: ls -R ./public
      - name: Verify Theme Files Exist
        run: ls -R ./themes/PaperMod
      - name: Hugo Environment Info
        run: hugo env


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

